//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVEEMPRPT
    {
        public string AppUser { get; set; }
        public long Pin_Code { get; set; }
        public Nullable<short> Timezone_Code { get; set; }
        public string HierCode { get; set; }
        public string Desigs { get; set; }
        public string Nation { get; set; }
        public string Religion { get; set; }
        public string EName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    }
}
