//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyDesc
    {
        public int CompanyDetailId { get; set; }
        public int userId { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Industry { get; set; }
        public string BuisenesNo { get; set; }
        public string EmployeeNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string AdminContact { get; set; }
        public string BillingContact { get; set; }
        public string support { get; set; }
        public string originatorId { get; set; }
        public string DataCenter { get; set; }
        public int CompanyId { get; set; }
    }
}
