//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_REC
    {
        public long Pin_Code { get; set; }
        public Nullable<long> CardID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Nation_Code { get; set; }
        public Nullable<int> Relig_Code { get; set; }
        public Nullable<int> Desigs_Code { get; set; }
        public Nullable<int> StatCode { get; set; }
        public Nullable<int> QualCode { get; set; }
        public string Mer_Stat { get; set; }
        public string B_Date { get; set; }
        public string J_Date { get; set; }
        public string R_Date { get; set; }
        public Nullable<short> Timezone_Code { get; set; }
        public string TZone_Status { get; set; }
        public Nullable<byte> Service_Stat { get; set; }
        public Nullable<byte> AutoFill { get; set; }
        public Nullable<byte> FlexTime { get; set; }
        public Nullable<byte> PunchOnce { get; set; }
        public string UsrTemplate { get; set; }
        public Nullable<short> Reject { get; set; }
        public Nullable<short> Authority { get; set; }
        public string Email { get; set; }
        public string HierCode { get; set; }
        public Nullable<short> GraceMins { get; set; }
        public Nullable<int> PlanCode { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Zipcode { get; set; }
        public string Address { get; set; }
    }
}
