//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupApplication
    {
        public int GroupApplicationId { get; set; }
        public int GroupRoleId { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual GroupRole GroupRole { get; set; }
    }
}
