//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDTSRPT
    {
        public string AppUser { get; set; }
        public long Pin_Code { get; set; }
        public string EName { get; set; }
        public string HierCode { get; set; }
        public string Desig { get; set; }
        public Nullable<System.DateTime> P_Date { get; set; }
        public string IN1 { get; set; }
        public string OUT1 { get; set; }
        public string IN2 { get; set; }
        public string OUT2 { get; set; }
        public string IN3 { get; set; }
        public string OUT3 { get; set; }
        public string IN4 { get; set; }
        public string OUT4 { get; set; }
        public string IN5 { get; set; }
        public string OUT5 { get; set; }
        public string IN6 { get; set; }
        public string OUT6 { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string Day_Status { get; set; }
        public string Mod_Field { get; set; }
        public string Overtime { get; set; }
        public Nullable<int> ExMins { get; set; }
        public Nullable<int> LateMins { get; set; }
        public Nullable<int> GraceMins { get; set; }
        public string TZoneIn1 { get; set; }
        public Nullable<long> WorkMins { get; set; }
        public Nullable<long> BreakMins { get; set; }
    }
}
