//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROT_TZONE
    {
        public long Pin_Code { get; set; }
        public short TZone_Code { get; set; }
        public short TZone_Code2 { get; set; }
        public Nullable<short> TZone_Code3 { get; set; }
        public System.DateTime From_Date { get; set; }
        public byte Days { get; set; }
        public byte Holidays { get; set; }
        public byte HoliMode { get; set; }
    }
}
