//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUMRPT
    {
        public string AppUser { get; set; }
        public long Pin_Code { get; set; }
        public string EName { get; set; }
        public Nullable<decimal> FriOV { get; set; }
        public Nullable<decimal> RegOV { get; set; }
        public Nullable<int> Absent { get; set; }
        public string Late { get; set; }
        public Nullable<short> SickReason { get; set; }
        public Nullable<short> PayReason { get; set; }
        public Nullable<short> OtherReason { get; set; }
        public Nullable<int> LateDays { get; set; }
        public Nullable<int> Late1 { get; set; }
        public Nullable<int> WHours { get; set; }
        public string WHoursStr { get; set; }
    }
}
