//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_TXT_DATA
    {
        public short ReaderID { get; set; }
        public long Pin_Code { get; set; }
        public System.DateTime P_Date { get; set; }
        public string P_Time { get; set; }
        public short TACode { get; set; }
    }
}
