//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_SHEET
    {
        public long Pin_Code { get; set; }
        public System.DateTime P_Date { get; set; }
        public string IN1 { get; set; }
        public string OUT1 { get; set; }
        public string IN2 { get; set; }
        public string OUT2 { get; set; }
        public string IN3 { get; set; }
        public string OUT3 { get; set; }
        public string IN4 { get; set; }
        public string OUT4 { get; set; }
        public string IN5 { get; set; }
        public string OUT5 { get; set; }
        public string IN6 { get; set; }
        public string OUT6 { get; set; }
        public short Timezone_Code { get; set; }
        public Nullable<byte> Pending { get; set; }
        public Nullable<int> Calen_Day { get; set; }
        public Nullable<int> Reas_Code { get; set; }
        public string Last_Punch { get; set; }
        public string Mod_Fields { get; set; }
        public byte Day_Status { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<byte> TranCount { get; set; }
    }
}
