//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEZONE
    {
        public short Timezone_Code { get; set; }
        public string Description { get; set; }
        public string IN1 { get; set; }
        public string OUT1 { get; set; }
        public string IN2 { get; set; }
        public string OUT2 { get; set; }
        public string IN3 { get; set; }
        public string OUT3 { get; set; }
        public Nullable<byte> Shifts { get; set; }
        public string HalfDayOut { get; set; }
        public string Working_Days { get; set; }
        public string Half_Days { get; set; }
        public string Holi_Days { get; set; }
        public byte NightShift { get; set; }
        public string HalfDayIn { get; set; }
    }
}
