//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSMODLOG
    {
        public string AppUser { get; set; }
        public long Pin_Code { get; set; }
        public System.DateTime TSDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public System.DateTime ModTime { get; set; }
        public string ModReas { get; set; }
    }
}
