//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAtten.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TZONERPT
    {
        public string AppUser { get; set; }
        public long Pin_Code { get; set; }
        public Nullable<System.DateTime> P_Date { get; set; }
        public string EName { get; set; }
        public string HierCode { get; set; }
        public string Desig { get; set; }
        public short Timezone_Code { get; set; }
        public string In1 { get; set; }
        public string Out1 { get; set; }
        public string In2 { get; set; }
        public string Out2 { get; set; }
        public string In3 { get; set; }
        public string Out3 { get; set; }
        public Nullable<byte> Shifts { get; set; }
        public string HalfDayOut { get; set; }
        public string Working_Days { get; set; }
        public string Half_Days { get; set; }
        public string Holi_Days { get; set; }
        public Nullable<byte> NighShift { get; set; }
        public string HalfDayIn { get; set; }
    }
}
